apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp
spec:
  replicas: 3
  selector:
    app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavacontainer
        image: ramanabolem/myjavaapp20oct22:1
        ports:
        - containerPort: 8080
