apiVersion: v1
kind: Service
metadata:
  name: maha-svc
  labels:
    app: myjavaapp
    Version: 2.6.1s
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp
    Version: 2.6.1 
